target:
  baseUrl: "https://reqres.in"
  environment: "external-demo"
  defaultHeaders:
    "Content-Type": "application/json"
    "Accept": "application/json"

totalVus: 100  # <--- This is what your main.js needed to do the math!

auth:
  type: "api-key"
  header: "x-api-key"
  token:
    envVar: "REQRES_API_KEY"

scenarios:
  - name: "fetch-users-list"
    endpoint: "/api/users?page=2"
    method: "GET"
    trafficShape: "smoke"
    weight: 40

  - name: "create-new-user"
    endpoint: "/api/users"
    method: "POST"
    trafficShape: "smoke"
    weight: 30
    payload:
      type: "static"
      data:
        name: "test_engineer"
        job: "performance_architect"

  - name: "update-existing-user"
    endpoint: "/api/users/2"
    method: "PUT"
    trafficShape: "smoke"
    weight: 20
    payload:
      type: "static"
      data:
        name: "test_engineer"
        job: "senior_performance_architect"

  - name: "delete-user"
    endpoint: "/api/users/2"
    method: "DELETE"
    trafficShape: "smoke"
    weight: 10

thresholds:
  p95_latency: 800
  error_rate: 0.05